import { Metadata } from "next";
import Link from "next/link";

interface SharePageProps {
  params: { "session-id": string };
}

// In production this would fetch from DB/KV store using session-id
// For MVP: encode data in URL via base64 or use KV storage
async function getSessionData(sessionId: string) {
  // Placeholder — real implementation reads from Supabase/KV
  return null;
}

export async function generateMetadata({ params }: SharePageProps): Promise<Metadata> {
  return {
    title: "Shared Hooks — HookGen.ai",
    description: "Check out these viral UGC hooks generated by HookGen.ai",
    openGraph: {
      title: "Viral UGC Hooks — HookGen.ai",
      description: "25 scroll-stopping hooks generated in 30 seconds",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: "Viral UGC Hooks — HookGen.ai",
      description: "25 scroll-stopping hooks generated in 30 seconds",
    },
  };
}

export default async function SharePage({ params }: SharePageProps) {
  const sessionId = params["session-id"];
  const data = await getSessionData(sessionId);

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      {/* Header */}
      <header className="border-b border-gray-800 px-4 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-xl font-bold">
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-pink-500">
              HookGen
            </span>
            <span className="text-white">.ai</span>
          </Link>
          <Link
            href="/generate"
            className="bg-orange-500 hover:bg-orange-400 text-white text-sm font-semibold px-4 py-2 rounded-xl transition-colors"
          >
            Generate Your Own →
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        {data ? (
          <div>
            {/* Session data display — populated from DB in production */}
            <h1 className="text-3xl font-bold mb-8">Shared Hook Set</h1>
            <pre className="text-gray-400 text-sm">{JSON.stringify(data, null, 2)}</pre>
          </div>
        ) : (
          <div className="text-center py-20">
            <div className="text-6xl mb-6">🎯</div>
            <h1 className="text-3xl font-bold mb-4">Viral UGC Hooks</h1>
            <p className="text-gray-400 mb-2 text-lg">Session ID: <code className="text-orange-400 font-mono">{sessionId}</code></p>
            <p className="text-gray-500 mb-8">
              This hook set was generated with HookGen.ai.
              <br />
              Generate your own viral hooks for free — 10 sets/day, no signup.
            </p>

            {/* Sample hooks to demonstrate value */}
            <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 mb-8 text-left">
              <p className="text-gray-400 text-sm mb-4 font-medium">
                Example output from HookGen.ai:
              </p>
              <div className="space-y-3">
                {[
                  "POV: I tried 47 products before finding the one that actually worked...",
                  "Dermatologists don't want you to know this costs under ₹1,000",
                  "I'm 42 and people think I'm 30. Here's my exact routine 👇",
                  "This one product cleared 8 years of damage in 60 days. No cap.",
                  "My before/after is insane and I'm still not over it 😭",
                ].map((hook, i) => (
                  <div key={i} className="flex items-start gap-3 bg-gray-800/50 rounded-xl p-3">
                    <span className="text-orange-400 font-bold text-sm min-w-[28px]">#{i + 1}</span>
                    <span className="text-gray-200 text-sm">{hook}</span>
                  </div>
                ))}
              </div>
            </div>

            <Link
              href="/generate"
              className="inline-flex items-center gap-2 bg-gradient-to-r from-orange-500 to-pink-500 hover:from-orange-400 hover:to-pink-400 text-white font-bold px-8 py-4 rounded-2xl text-lg transition-all transform hover:scale-105"
            >
              Generate Hooks for YOUR Product — Free →
            </Link>
            <p className="text-gray-500 text-sm mt-3">
              10 hook sets/day free · No signup · No credit card
            </p>
          </div>
        )}
      </main>
    </div>
  );
}
